### ISSUE TITLE
i5 13400f + ax6600 是否可以兼容

### ISSUE THREAD

**Issue by uhaorph1636** [jfsunx/ASUS_TUF_GAMING_B760M_PLUS_WiFi_D4_Hackintosh#1]
大佬？我们主板是一样的，但是我的CPU是 i5 13400f。显卡是 ax6600 可以直接用吗？还是要修改一些地方。

**Comment by jfsunx** [comment]
应该是可以直接使用的。安装时可开启-v模式以便排查故障，如果成功了请重新生成序列号以登录苹果账号。





------------------ 原始邮件 ------------------
发件人: uhaorph1636 ***@***.***&gt;
发送时间: 2023年7月21日 18:48
收件人: jfsunx/ASUS_TUF_GAMING_B760M_PLUS_WiFi_D4_Hackintosh ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [jfsunx/ASUS_TUF_GAMING_B760M_PLUS_WiFi_D4_Hackintosh] i5 13400f + ax6600 是否可以兼容 (Issue #1)





 
大佬？我们主板是一样的，但是我的CPU是 i5 13400f。显卡是 ax6600 可以直接用吗？还是要修改一些地方。

**Comment by jfsunx** [comment]
应该是可以直接使用的。安装时可开启-v模式以便排查故障，如果成功了请重新生成序列号以登录苹果账号。

> 从12.1开始，苹果增加了对RX 6600 XT的支持。
支持的卡:
RX 6600
RX 6600 XT
Note: Most Navi 23 cards currently require the boot argument `agdpmod=pikera` to get a display out.
需要的kext:
[Lilu.kext(opens new window)](https://github.com/acidanthera/Lilu/releases)
[WhateverGreen.kext](https://github.com/acidanthera/WhateverGreen/releases)

**Comment by uhaorph1636** [comment]
好的 感谢
